//types of fetching products action
export const FETCH_PRODUCTS_DATA = 'FETCH_PRODUCTS_DATA';
export const FETCH_PRODUCTS_DATA_SUCCESS =
  'FETCH_PRODUCTS_DATA_SUCCESS';
export const FETCH_PRODUCTS_DATA_FAIL = 'FETCH_PRODUCTS_DATA_FAIL';
//types of products detail action
export const FETCH_PRODUCTS_DETAILS = 'FETCH_PRODUCTS_DETAILS';
export const FETCH_PRODUCTS_DETAILS_SUCCESS =
  'FETCH_PRODUCTS_DETAILS_DATA_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_FAIL =
  'FETCH_PRODUCTS_DETAILS_DATA_FAIL';
//types of add OR remove to/from cart action
export const ADD_TO_CART_ITEMS = 'ADD_TO_CART_PRODUCT';
export const REMOVE_FROM_CART_ITEMS = 'REMOVE_FROM_CART_ITEMS';
//types of user signin, signout and register action
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
//shipping address action
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS';
//Payment method action action
export const SAVE_PAYMENT = 'SAVE_PAYMENT';
//types of order action
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET';
export const DETAILS_ORDER_REQUEST = 'DETAILS_ORDER_REQUEST';
export const DETAILS_ORDER_SUCCESS = 'DETAILS_ORDER_SUCCESS';
export const DETAILS_ORDER_FAIL = 'DETAILS_ORDER_FAIL';
export const CART_EMPTY = 'CART_EMPTY';
//types of user order list
export const MINE_ORDER_LIST_REQUEST = 'MINE_ORDER_LIST_REQUEST';
export const MINE_ORDER_LIST_SUCCESS = 'MINE_ORDER_LIST_SUCCESS';
export const MINE_ORDER_LIST_FAIL = 'MINE_ORDER_LIST_FAIL';
