//types of fetching products
export const FETCH_PRODUCTS_DATA = 'FETCH_PRODUCTS_DATA';
export const FETCH_PRODUCTS_DATA_SUCCESS =
  'FETCH_PRODUCTS_DATA_SUCCESS';
export const FETCH_PRODUCTS_DATA_FAIL = 'FETCH_PRODUCTS_DATA_FAIL';
//types of products detail
export const FETCH_PRODUCTS_DETAILS = 'FETCH_PRODUCTS_DETAILS';
export const FETCH_PRODUCTS_DETAILS_SUCCESS =
  'FETCH_PRODUCTS_DETAILS_DATA_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_FAIL =
  'FETCH_PRODUCTS_DETAILS_DATA_FAIL';
//types of add OR remove to/from cart
export const ADD_TO_CART_ITEMS = 'ADD_TO_CART_PRODUCT';
export const REMOVE_FROM_CART_ITEMS = 'REMOVE_FROM_CART_ITEMS';
