export const FETCH_PRODUCTS_DATA = 'FETCH_PRODUCTS_DATA';
export const FETCH_PRODUCTS_DATA_SUCCESS =
  'FETCH_PRODUCTS_DATA_SUCCESS';
export const FETCH_PRODUCTS_DATA_FAIL = 'FETCH_PRODUCTS_DATA_FAIL';

export const FETCH_PRODUCTS_DETAILS = 'FETCH_PRODUCTS_DETAILS';
export const FETCH_PRODUCTS_DETAILS_SUCCESS =
  'FETCH_PRODUCTS_DETAILS_DATA_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_FAIL =
  'FETCH_PRODUCTS_DETAILS_DATA_FAIL';
